#! /bin/sh

# --- QT/THEME FIX ---
# Fuerza XCB para evitar bordes rotos en BSPWM y Kvantum para unificar temas
export QT_QPA_PLATFORM=xcb
export QT_STYLE_OVERRIDE=kvantum
export QT_QPA_PLATFORMTHEME=qt5ct
# Iniciar Portals necesarios para Qt6
(sleep 1; /usr/lib/xdg-desktop-portal &)
(sleep 1; /usr/lib/xdg-desktop-portal-gtk &)
# ------------------------------------------------

# --- Configuración del SSH-Agent ---

# Inicia el agente solo si no está corriendo.
pgrep -u "$USER" ssh-agent > /dev/null || ssh-agent -s > /tmp/ssh-agent.sh

# Carga las variables de entorno.
[ -f /tmp/ssh-agent.sh ] && . /tmp/ssh-agent.sh

# --- Resto de la configuración de bspwm ---
bspc monitor -d I II III IV V

xsetroot -cursor_name left_ptr
bspc config border_width        2
bspc config window_gap          3
bspc config top_padding 		20

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      true

bspc config focus_follows_pointer true 

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side

bspc rule -a megasync state=floating rectangle=600x450+0+0 center=on sticky=on follow=on
bspc rule -a Nm-applet state=floating center=on
bspc rule -a Nm-connection-editor state=floating center=on

bspc rule -a Pavucontrol state=floating center=on
bspc rule -a Blueberry state=floating center=on
bspc rule -a Pluma state=floating center=on
bspc rule -a mpv state=floating   
bspc rule -a VLC state=floating

bspc rule -a Rofi state=floating center=on

# Essential Startup
pgrep picom >/dev/null || picom &
pgrep sxhkd >/dev/null || sxhkd &
pgrep feh >/dev/null || feh --bg-fill ~/.config/bspwm/wallpaper.png &
~/.config/polybar/launch.sh &

#Support for custom startup
~/.config/bspwm/start.sh &

# Terminar np-applet y metasync si están corriendo
pgrep np-applet && pkill np-applet
pgrep megasync && pkill megasync
pgrep polkit-gnome-authentication-agent-1 && pkill polkit-gnome-authentication-agent-1

# Iniciar aplicaciones necesarias
pgrep nm-applet || nm-applet &
pgrep megasync || megasync &
pgrep polkit-gnome-authentication-agent-1 || /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
pgrep blueberry-tray || blueberry-tray &

# Desactiva el curso si no lo estás usando.
pgrep unclutter || unclutter -idle 5 -root &

# Inicia conky
killall -q conky
(sleep 3 && conky -c /home/netenebrae/.config/conky/conky.conf) &

# Lock screen 
pgrep xautolock || xautolock -time 5 -locker "betterlockscreen -l" &

# Configuración de pantalla (Evita suspensión, apaga a la hora)
xset s off               # Desactiva el protector de pantalla clásico
xset -dpms               # Resetea DPMS
xset dpms 0 0 3600 &     # 0 standby, 0 suspend, 3600 (1 hora)
