#! /bin/sh
# --- Configuración del SSH-Agent ---
# Inicia el agente solo si no está corriendo.
pgrep -u "$USER" ssh-agent > /dev/null || ssh-agent -s > /tmp/ssh-agent.sh

# Carga las variables de entorno.
[ -f /tmp/ssh-agent.sh ] && . /tmp/ssh-agent.sh

# Opcional: Cargar la clave después de iniciar el agente.
# Esto solo funcionará si bspwmrc puede manejar la entrada de la contraseña (lo que no suele ser el caso).
# Es más seguro hacer el 'ssh-add' en el shell la primera vez.

# --- Resto de la configuración de bspwm ---


pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        2
bspc config window_gap          3
bspc config top_padding 25

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off


# EL SAVITAR + EL TENE
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
sxhkd &
xsettingsd &
picom &
feh --bg-fill /home/netenebrae/Pictures/Wallpapers/anime-girl-red-eyes-white-hair-8k-wallpaper-uhdpaper.com-264\@5\@b.jpg 

~/.config/polybar/./launch.sh

bspc config focus_follows_pointer true
